### ISSUE TITLE
[BUG] Re-selecting Character

### ISSUE THREAD

**Issue by ZheinGlitch** [aosyatnik/Imgeneus#13]
So here is the flows:
Select Character > Game Start > Loading Screen -> You're now in the game.

But when you logged out (Change Character)

Log out -> Select Character (Another Toon) -> Game Start -> Loading Screen -> You're now in game

What happen is that, both of your toons (The first toon you opened, and the toon that you recently opened will be summoned in game)

**Comment by aosyatnik** [comment]
Hi, @ZheinGlitch , thank you for your feedback. I'm tracking this bug in trello. :)

**Comment by aosyatnik** [comment]
Fixed.
