### ISSUE TITLE
Add notice messages and gm commands for them

### ISSUE THREAD

**Issue by matigramirez** [aosyatnik/Imgeneus#3]
Notices can be used by admins via in-game commands but are also used to indicate server events such as GRB, Oblivion Insula opening/closing, server promotions, game events, etc.

In-game commands have some variations which include (the ones I'm aware of):

1.  **`/notice time "message"`**:  Sends a notice to **all players**
    - `time` : optional `2 byte` parameter, which reproduces the notice every `time`  in **seconds**
    - `"message"`: message string, **must** be between double quotes

2. **`/wnotice Charname “message”`**: Sends a notice to a **specific character**
    - `Charname`: target character's name, doesn't need double quotes 
    - `"message"`: message string, **must** be between double quotes

3. **`/znotice “message”`**:  Sends a notice to all players in the **map** the sender is located at
    - `"message"`: message string, **must** be between double quotes

4. **`/cnotice “message”`**:  Sends a notice to all players that belong to the sender's **faction**
    - `"message"`: message string, **must** be between double quotes

5. **`/gmnotice “message”`**:  Sends a notice to all **GM's**
    - `"message"`: message string, **must** be between double quotes

With this in mind, I propose the creation of the following methods:
- **WorldNotice**
- **PlayerNotice**
- **MapNotice**
- **FactionNotice**
- **GMNotice**
- **NotInMapNotice**: personally I think a method that sends a notice to all players that aren't in a certain map could be useful in certain situations. It could have a list of maps as parameter to avoid sending notices to players that are in those maps.
- **WithinRangeNotice**: I don't really remember how boss notices work (or if they are notices per-se) but some have AI's that display messages when they're attacked, reach certain HP, etc. These "notices" are received only by players within the range of the boss

These methods should be globally available since, as mentioned earlier, they are used both for gm commands and server events.
I propose the creation of an injectable service similar to the ChatManager service for this.

**Comment by aosyatnik** [comment]
I think it's a good idea to have a separate service or manager for notices. Yes, this can be done the same way as `ChatManager`.

**Comment by matigramirez** [comment]
6. **`/bnotice`** is missing in the list but for the moment, I haven't been able to find the right parameters for it. It's supposed to be used to send a notice to a map cell in particular by providing `x` and `z` coordinates.

**Comment by matigramirez** [comment]
`/bnotice` is part of the chinese client only so there's no need to implement it.
Boss notices work differently to normal notices so they should be done separately.
Timers are missing for a future update.
