### ISSUE TITLE
Chaotic Square

### ISSUE THREAD

**Issue by ZheinGlitch** [aosyatnik/Imgeneus#50]
I just want to share this Packet Structure of Chaotic Square. By sharing this structure, I hope others can help me identify this this packets that I labeled as unknown.

![image](https://user-images.githubusercontent.com/75904474/107788920-ea141b00-6d8b-11eb-89a8-92c0bcc89dc9.png)

**CLIENT TO SERVER**
Note: Generated when you opened chaotic square item.
OP CODE = 30 08
UNKNOWN = 01
UNKNOWN = 05

**SERVER TO CLIENT**
Note: Limited to 10 items only, resend the packet if you want more.
OP CODE: 30 08 
ITEM_TYPE_1 = 26
ITEM_TYPE_2 = 26
ITEM_TYPE_3 = 00
ITEM_TYPE_4 = 00
ITEM_TYPE_5 = 00
ITEM_TYPE_6 = 00
ITEM_TYPE_7 = 00
ITEM_TYPE_8 = 00
ITEM_TYPE_9 = 00
ITEM_TYPE_10 = 00
ITEM_ID_1 = 12
ITEM_ID_2 = 08
ITEM_ID_3 = 00
ITEM_ID_4 = 00
ITEM_ID_5 = 00
ITEM_ID_6 = 00
ITEM_ID_7 = 00
ITEM_ID_8 = 00
ITEM_ID_9 = 00
ITEM_ID_10 = 00
ITEM_QUANTITY_1 = 01
ITEM_QUANTITY_2 = 01
ITEM_QUANTITY_3 = 00
ITEM_QUANTITY_4 = 00
ITEM_QUANTITY_5 = 00
ITEM_QUANTITY_6 = 00
ITEM_QUANTITY_7 = 00
ITEM_QUANTITY_8 = 00
ITEM_QUANTITY_9 = 00
ITEM_QUANTITY_10 = 00

![image](https://user-images.githubusercontent.com/75904474/107788990-fd26eb00-6d8b-11eb-86b2-bc31a5ea1d9f.png)

**CLIENT TO SERVER**
Note: Generated when you click on the list on the Chaotic Square.
OP CODE = 31 08
ITEM_TYPE =  78
ITEM_ID = 0B

**SERVER TO CLIENT**
Note: Limited to 24 items only.
OP CODE = 31 08
RATE_WHOLE = 0A // 62 or 62.22 %
RATE_POINT = 1B //22 or 62.22 %
UNKNOWN = 00
UNKNOWN = 00
ITEM_TYPE_1 = 10
ITEM_TYPE_2 = 27
ITEM_TYPE_3 = 00
ITEM_TYPE_4 = 00
ITEM_TYPE_5 = 00
ITEM_TYPE_6 = 00
ITEM_TYPE_7 = 00
ITEM_TYPE_8 = 00
ITEM_TYPE_9 = 00
ITEM_TYPE_10 = 00
ITEM_TYPE_11 = 00
ITEM_TYPE_12 = 00
ITEM_TYPE_13 = 00
ITEM_TYPE_14 = 00
ITEM_TYPE_15 = 00
ITEM_TYPE_16 = 00
ITEM_TYPE_17 = 00
ITEM_TYPE_18 = 00
ITEM_TYPE_19 = 00
ITEM_TYPE_20 = 00
ITEM_TYPE_21 = 00
ITEM_TYPE_22 = 00
ITEM_TYPE_23 = 00
ITEM_TYPE_24 = 00
UNKNOWN = 78  //Theory: This might be the Item Type for the reward.
ITEM_ID_1 = 12
ITEM_ID_2 = 08
ITEM_ID_3 = 00
ITEM_ID_4 = 00
ITEM_ID_5 = 00
ITEM_ID_6 = 00
ITEM_ID_7 = 00
ITEM_ID_8 = 00
ITEM_ID_9 = 00
ITEM_ID_10 = 00
ITEM_ID_11 = 00
ITEM_ID_12 = 00
ITEM_ID_13 = 00
ITEM_ID_14 = 00
ITEM_ID_15 = 00
ITEM_ID_16 = 00
ITEM_ID_17 = 00
ITEM_ID_18 = 00
ITEM_ID_19 = 00
ITEM_ID_20 = 00
ITEM_ID_21 = 00
ITEM_ID_22 = 00
ITEM_ID_23 = 00
ITEM_ID_24 = 00
UNKNOWN = 0B //Theory: This might be the Item ID for the reward.
ITEM_QUANTITY_1 = 02
ITEM_QUANTITY_2 = 02
ITEM_QUANTITY_3 = 00
ITEM_QUANTITY_4 = 00
ITEM_QUANTITY_5 = 00
ITEM_QUANTITY_6 = 00
ITEM_QUANTITY_7 = 00
ITEM_QUANTITY_8 = 00
ITEM_QUANTITY_9 = 00
ITEM_QUANTITY_10 = 00
ITEM_QUANTITY_11 = 00
ITEM_QUANTITY_12 = 00
ITEM_QUANTITY_13 = 00
ITEM_QUANTITY_14 = 00
ITEM_QUANTITY_15 = 00
ITEM_QUANTITY_16 = 00
ITEM_QUANTITY_17 = 00
ITEM_QUANTITY_18 = 00
ITEM_QUANTITY_19 = 00
ITEM_QUANTITY_20 = 00
ITEM_QUANTITY_21 = 00
ITEM_QUANTITY_22 = 00
ITEM_QUANTITY_23 = 00
ITEM_QUANTITY_24 = 00
UNKNOWN = 01 //Theory: This might be the Quantity for the reward.

**CLIENT TO SERVER**
Note: Generated when you pressed combine.
OP CODE = 32 08
UNKNOWN = 01
UNKNOWN = 06
UNKNOWN = 00
UNKNOWN = 00
UNKNOWN = 00
UNKNOWN = 00
UNKNOWN = 01
UNKNOWN = 00
UNKNOWN = 00
UNKNOWN = 00
UNKNOWN = 00
UNKNOWN = 00

**SERVER TO CLIENT**
OP CODE = 32 08

**Comment by aosyatnik** [comment]
Cool! Thank you very much. Hopefully, we can implement it one day 😄 I'll keep it open till this feature is implemented. Thanks for the collaboration :)

**Comment by aosyatnik** [comment]
And welcome to "Hall of fame" :)

**Comment by aosyatnik** [comment]
Implemented.
