### ISSUE TITLE
[REQUEST] World Editor

### ISSUE THREAD

**Issue by ZheinGlitch** [aosyatnik/Imgeneus#61]
Have you heard the Flyff World Editor? The game is somewhat similar to Shaiya and maybe we can modify some things so we can edit the maps. I've seen someone who did it already.

Here is it:
https://www.youtube.com/watch?v=bgIgThsBkTk

Source Code:
https://github.com/Yothri/ATools/tree/master/WorldEditor

Recreating Shaiya is cool and I think making a tool that allows us to edit the maps would be even more cooler. Well, there are a lot of tools already that we can edit a map but most of it is very old which is not a problem for it is still working.

**Comment by aosyatnik** [comment]
Imgeneus is meant only for server. As world definition is client side information, it's not gonna be implemented in server emulator any time soon. Maybe one day in Parsec... But I'm closing this issue, as it's client side feature request.
