### ISSUE TITLE
[HELP] Cannot login

### ISSUE THREAD

**Issue by ZheinGlitch** [aosyatnik/Imgeneus#9]
Hi, I've been trying to cope with the program so I can help however I am facing problem in logging in. Yeah2, if I can't fix login, how much more in the game. But I want to ask if is it because I am using different game.exe with you guys or game.exe doesn't matter? If I'm using different game.exe, please send me the correct one. Thanks!

Client Used: Shaiya US (Latest Update)
Game.exe used: [here](https://www.elitepvpers.com/forum/shaiya-pserver-guides-releases/4137555-shaiya-us-unpack-ep8-game-updater-exe.html)

I have an account created already in database. But every time I log in game, it freezes and later "Cannot Received Login Data". I hope you will notice this problem of mine 👍 

![image](https://user-images.githubusercontent.com/75904474/101989462-62525780-3cdb-11eb-8e6c-a1b972ae2fb1.png)
![image](https://user-images.githubusercontent.com/75904474/101989476-7f872600-3cdb-11eb-81df-926fab96df12.png)
![image](https://user-images.githubusercontent.com/75904474/101989494-a80f2000-3cdb-11eb-911b-2accb2ad6c0c.png)

**Comment by matigramirez** [comment]
Change your your user `Status` to `0` and try again. Also make sure you've followed all the instructions on the `Build and Run` section on the readme.

**Comment by ZheinGlitch** [comment]
> Change your your user `Status` to `0` and try again. Also make sure you've followed all the instructions on the `Build and Run` section on the readme.

Yeah, I figured it out already but I encounter new problem which GameGuard, how to remove the game guard, do you have any game exe?
![image](https://user-images.githubusercontent.com/75904474/101989927-8b281c00-3cde-11eb-9d1f-8b10815c4dc4.png)

**Comment by matigramirez** [comment]
I can't really link you to any resource directly here but a quick search on epvp for `shaiya ep8 game` should get you what you need

**Comment by matigramirez** [comment]
I just saw you edited your first post and linked to what client/game you're using. Latest US client might have some integrated security for the game, try removing files or download another version of the client, also from epvp.

**Comment by matigramirez** [comment]
If you want to drop your email/discord here I can assist you further.

**Comment by ZheinGlitch** [comment]
Discord ID: 690588326368903248

**Comment by aosyatnik** [comment]
Good day, I'm closing this issue, since this repo is not about breaking game security or any game hacks. I strongly recommend not to post any links to hacked exe files. You can contact me or Mati via email or discord for more info. We don't endorse game cheating or hacking any game guard. Thank you!
